// Generated by CoffeeScript 1.6.3
(function() {
  var Box, root;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  Box = (function() {
    function Box(point, parent) {
      this.parent = parent;
      this.id = "box_" + new Date().getTime();
      this.point = {};
      this.point.x = point[0], this.point.y = point[1];
      this.buildBox();
    }

    Box.prototype.buildBox = function() {
      var div;
      div = $("<div class=\"box\" id=\"" + this.id + "\">").css({
        height: 20,
        width: 20,
        position: 'absolute',
        top: this.point.y - 10,
        left: this.point.x - 10,
        display: 'none',
        backgroundColor: "rgb(" + (_.random(0, 255)) + ", " + (_.random(0, 255)) + ", " + (_.random(0, 255)) + ")"
      });
      this.parent.append(div);
      return this;
    };

    Box.prototype.showBox = function() {
      return this.parent.find("#" + this.id).fadeIn('fast');
    };

    Box.prototype.hideBox = function() {
      return this.parent.find("#" + this.id).fadeOut('fast', function() {
        return $(this).remove();
      });
    };

    return Box;

  })();

  if (typeof module === 'object' && module && typeof module.exports === 'object') {
    module.exports = Box;
  } else if (typeof exports === 'object' && exports) {
    exports.Box = Box;
  } else if (typeof define === 'function' && define.amd) {
    define('box', [], function() {
      return Box;
    });
  } else {
    root.Box = Box;
  }

}).call(this);
